services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3333:3333'
    volumes:
      - ./access.log:/app/access.log
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - default
      - squidex_net

networks:
  default:
    driver: bridge
  squidex_net:
    external: true
    name: squidex_squidex_net
